# Generated by Django 6.0 on 2026-01-10 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_posting', '0018_applicationtable_flag_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationtable',
            name='interview_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applicationtable',
            name='interview_step',
            field=models.IntegerField(default=0),
        ),
    ]
