# Generated by Django 4.2.27 on 2026-01-17 08:21

import candidates.models
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_type', models.CharField(choices=[('candidate', 'Candidate'), ('hr', 'HR Recruiter')], default='candidate', help_text='User type: Candidate or HR Recruiter', max_length=20)),
                ('phone', models.CharField(blank=True, help_text='Phone number', max_length=20, null=True)),
                ('company', models.CharField(blank=True, help_text='Company name (for HR users)', max_length=255, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Candidate's full name", max_length=255)),
                ('email', models.EmailField(help_text="Candidate's email address", max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, help_text="Candidate's phone number", max_length=20, null=True)),
                ('resume', models.FileField(blank=True, help_text='Resume file (PDF, DOCX, TXT, DOC)', null=True, upload_to=candidates.models.resume_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'txt', 'doc'])])),
                ('parsed_text', models.TextField(blank=True, help_text='Raw extracted text from resume', null=True)),
                ('parsed_name', models.CharField(blank=True, help_text='Name extracted from resume', max_length=255, null=True)),
                ('parsed_email', models.EmailField(blank=True, help_text='Email extracted from resume', max_length=254, null=True)),
                ('parsed_phone', models.CharField(blank=True, help_text='Phone number extracted from resume', max_length=50, null=True)),
                ('parsed_linkedin', models.URLField(blank=True, help_text='LinkedIn profile URL', max_length=500, null=True)),
                ('parsed_github', models.URLField(blank=True, help_text='GitHub profile URL', max_length=500, null=True)),
                ('parsed_portfolio', models.URLField(blank=True, help_text='Portfolio/personal website URL', max_length=500, null=True)),
                ('parsed_other_links', models.JSONField(blank=True, default=list, help_text='Other professional links')),
                ('parsed_skills', models.JSONField(blank=True, default=list, help_text='Technical and professional skills')),
                ('parsed_languages', models.JSONField(blank=True, default=list, help_text='Programming languages')),
                ('parsed_frameworks', models.JSONField(blank=True, default=list, help_text='Frameworks and libraries')),
                ('parsed_tools', models.JSONField(blank=True, default=list, help_text='Tools and technologies')),
                ('parsed_experience', models.JSONField(blank=True, default=list, help_text='Work experience entries')),
                ('parsed_experience_years', models.FloatField(blank=True, default=0, help_text='Total years of experience')),
                ('parsed_current_position', models.CharField(blank=True, help_text='Current or most recent position', max_length=255, null=True)),
                ('parsed_current_company', models.CharField(blank=True, help_text='Current or most recent company', max_length=255, null=True)),
                ('parsed_education', models.JSONField(blank=True, default=list, help_text='Education history')),
                ('parsed_education_level', models.CharField(blank=True, help_text='Highest degree obtained', max_length=255, null=True)),
                ('parsed_university', models.CharField(blank=True, help_text='Most recent university/institution', max_length=255, null=True)),
                ('parsed_certifications', models.JSONField(blank=True, default=list, help_text='Professional certifications')),
                ('parsed_projects', models.JSONField(blank=True, default=list, help_text='Notable projects')),
                ('parsed_summary', models.TextField(blank=True, help_text='Professional summary/objective', null=True)),
                ('parsed_location', models.CharField(blank=True, help_text='Location/Address', max_length=255, null=True)),
                ('linkedin_url', models.URLField(blank=True, help_text='LinkedIn profile (user-provided)', null=True)),
                ('portfolio_url', models.URLField(blank=True, help_text='Portfolio website (user-provided)', null=True)),
                ('application_status', models.CharField(choices=[('applied', 'Applied'), ('screening', 'Screening'), ('interview', 'Interview'), ('rejected', 'Rejected'), ('hired', 'Hired')], default='applied', help_text='Current application status', max_length=50)),
                ('parsing_status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('partial', 'Partial')], default='pending', help_text='Resume parsing status', max_length=50)),
                ('parsing_error', models.TextField(blank=True, help_text='Error message if parsing failed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Application submission timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
                ('user', models.OneToOneField(blank=True, help_text='Linked user account', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Candidate',
                'verbose_name_plural': 'Candidates',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email'], name='candidates__email_188e48_idx'), models.Index(fields=['created_at'], name='candidates__created_a71da5_idx'), models.Index(fields=['application_status'], name='candidates__applica_c3576d_idx'), models.Index(fields=['parsing_status'], name='candidates__parsing_a7c81f_idx')],
            },
        ),
    ]
