# Generated by Django 4.2.27 on 2025-12-31 06:00

import candidates.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text="Candidate's full name", max_length=255)),
                ('email', models.EmailField(help_text="Candidate's email address (unique identifier)", max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, help_text="Candidate's phone number (optional)", max_length=20, null=True)),
                ('resume', models.FileField(help_text='Resume file (PDF, DOCX, TXT formats supported)', upload_to=candidates.models.resume_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'txt', 'doc'])])),
                ('parsed_text', models.TextField(blank=True, help_text='Raw extracted text from resume', null=True)),
                ('parsed_email', models.EmailField(blank=True, help_text='Email extracted from resume', max_length=254, null=True)),
                ('parsed_phone', models.CharField(blank=True, help_text='Phone number extracted from resume', max_length=20, null=True)),
                ('parsed_skills', models.JSONField(blank=True, default=list, help_text='List of skills extracted from resume')),
                ('application_status', models.CharField(choices=[('applied', 'Applied'), ('screening', 'Screening'), ('interview', 'Interview'), ('rejected', 'Rejected'), ('hired', 'Hired')], default='applied', help_text='Current application status', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when application was submitted')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
            ],
            options={
                'verbose_name': 'Candidate',
                'verbose_name_plural': 'Candidates',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email'], name='candidates__email_188e48_idx'), models.Index(fields=['created_at'], name='candidates__created_a71da5_idx'), models.Index(fields=['application_status'], name='candidates__applica_c3576d_idx')],
            },
        ),
    ]
