# Generated by Django 4.2.27 on 2026-01-01 19:08

import candidates.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='parsed_certifications',
            field=models.JSONField(blank=True, default=list, help_text='Professional certifications'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='parsed_current_company',
            field=models.CharField(blank=True, help_text='Current or most recent company', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='parsed_current_position',
            field=models.CharField(blank=True, help_text='Current or most recent position', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='parsed_education',
            field=models.JSONField(blank=True, default=list, help_text='Education history'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='parsed_experience',
            field=models.JSONField(blank=True, default=list, help_text='Work experience entries'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='parsed_frameworks',
            field=models.JSONField(blank=True, default=list, help_text='Frameworks and libraries'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='parsed_github',
            field=models.URLField(blank=True, help_text='GitHub profile URL', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='parsed_highest_degree',
            field=models.CharField(blank=True, help_text='Highest degree obtained', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='parsed_languages',
            field=models.JSONField(blank=True, default=list, help_text='Programming languages'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='parsed_linkedin',
            field=models.URLField(blank=True, help_text='LinkedIn profile URL', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='parsed_location',
            field=models.CharField(blank=True, help_text='Location/Address', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='parsed_name',
            field=models.CharField(blank=True, help_text='Name extracted from resume', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='parsed_other_links',
            field=models.JSONField(blank=True, default=list, help_text='Other professional links (Twitter, Stack Overflow, etc.)'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='parsed_portfolio',
            field=models.URLField(blank=True, help_text='Portfolio/personal website URL', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='parsed_projects',
            field=models.JSONField(blank=True, default=list, help_text='Notable projects'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='parsed_summary',
            field=models.TextField(blank=True, help_text='Professional summary/objective', null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='parsed_tools',
            field=models.JSONField(blank=True, default=list, help_text='Tools and technologies'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='parsed_total_experience_years',
            field=models.FloatField(blank=True, help_text='Total years of experience', null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='parsed_university',
            field=models.CharField(blank=True, help_text='Most recent university/institution', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='parsing_error',
            field=models.TextField(blank=True, help_text='Error message if parsing failed', null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='parsing_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('partial', 'Partial')], default='pending', help_text='Resume parsing status', max_length=50),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Application submission timestamp'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='email',
            field=models.EmailField(help_text="Candidate's email address", max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='parsed_phone',
            field=models.CharField(blank=True, help_text='Phone number extracted from resume', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='parsed_skills',
            field=models.JSONField(blank=True, default=list, help_text='Technical and professional skills'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='phone',
            field=models.CharField(blank=True, help_text="Candidate's phone number", max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='resume',
            field=models.FileField(help_text='Resume file', upload_to=candidates.models.resume_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'txt', 'doc'])]),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Last update timestamp'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['parsing_status'], name='candidates__parsing_a7c81f_idx'),
        ),
    ]
