# Generated by Django 4.2.27 on 2026-01-18 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='parsed_soft_skills',
            field=models.JSONField(blank=True, default=list, help_text='Soft skills (Communication, Leadership, etc.)'),
        ),
    ]
