# Generated by Django 4.2.27 on 2026-01-11 18:12

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('candidates', '0002_candidate_parsed_certifications_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('company_name', models.CharField(default='Your Company', max_length=200)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(help_text='Full job description')),
                ('responsibilities', models.TextField(blank=True, help_text='Key responsibilities')),
                ('requirements', models.TextField(blank=True, help_text='Required qualifications')),
                ('nice_to_have', models.TextField(blank=True, help_text='Preferred qualifications')),
                ('employment_type', models.CharField(choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('contract', 'Contract'), ('internship', 'Internship'), ('temporary', 'Temporary')], default='full_time', max_length=20)),
                ('experience_level', models.CharField(choices=[('entry', 'Entry Level'), ('mid', 'Mid Level'), ('senior', 'Senior Level'), ('lead', 'Lead/Principal'), ('executive', 'Executive')], default='mid', max_length=20)),
                ('min_experience_years', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)])),
                ('max_experience_years', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)])),
                ('location', models.CharField(max_length=200)),
                ('is_remote', models.BooleanField(default=False)),
                ('remote_type', models.CharField(choices=[('fully_remote', 'Fully Remote'), ('hybrid', 'Hybrid'), ('on_site', 'On-site')], default='on_site', max_length=20)),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum salary', max_digits=10, null=True)),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum salary', max_digits=10, null=True)),
                ('salary_currency', models.CharField(default='USD', max_length=3)),
                ('salary_period', models.CharField(choices=[('hourly', 'Hourly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='yearly', max_length=20)),
                ('parsed_required_skills', models.JSONField(blank=True, default=list, help_text='AI-extracted required skills')),
                ('parsed_preferred_skills', models.JSONField(blank=True, default=list, help_text='AI-extracted preferred skills')),
                ('parsed_qualifications', models.JSONField(blank=True, default=list, help_text='AI-extracted qualifications (degrees, certifications)')),
                ('parsed_responsibilities', models.JSONField(blank=True, default=list, help_text='AI-extracted key responsibilities')),
                ('parsed_benefits', models.JSONField(blank=True, default=list, help_text='AI-extracted benefits')),
                ('application_deadline', models.DateTimeField(blank=True, null=True)),
                ('max_applications', models.IntegerField(blank=True, help_text='Maximum number of applications to accept', null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('closed', 'Closed'), ('on_hold', 'On Hold')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('view_count', models.IntegerField(default=0)),
                ('application_count', models.IntegerField(default=0)),
                ('keywords', models.JSONField(blank=True, default=list, help_text='Keywords for search and matching')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job Posting',
                'verbose_name_plural': 'Job Postings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('screening', 'Under Screening'), ('shortlisted', 'Shortlisted'), ('interview_scheduled', 'Interview Scheduled'), ('interviewed', 'Interviewed'), ('offer_extended', 'Offer Extended'), ('hired', 'Hired'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='applied', max_length=30)),
                ('cover_letter', models.TextField(blank=True)),
                ('match_score', models.DecimalField(blank=True, decimal_places=2, help_text='AI-calculated match score (0-100)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('match_details', models.JSONField(blank=True, default=dict, help_text='Detailed matching breakdown')),
                ('screening_notes', models.TextField(blank=True)),
                ('screening_score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('interview_date', models.DateTimeField(blank=True, null=True)),
                ('interview_notes', models.TextField(blank=True)),
                ('interview_score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to='candidates.candidate')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job Application',
                'verbose_name_plural': 'Job Applications',
                'ordering': ['-applied_at'],
                'indexes': [models.Index(fields=['job', 'status'], name='jobs_jobapp_job_id_08192b_idx'), models.Index(fields=['-match_score'], name='jobs_jobapp_match_s_d65b26_idx')],
                'unique_together': {('job', 'candidate')},
            },
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['status', '-created_at'], name='jobs_job_status_57b86b_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['job_id'], name='jobs_job_job_id_fa7756_idx'),
        ),
    ]
