# Generated by Django 4.2.27 on 2026-01-17 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='jobapplication',
            options={'ordering': ['-match_score', '-applied_at']},
        ),
        migrations.RemoveIndex(
            model_name='job',
            name='jobs_job_status_57b86b_idx',
        ),
        migrations.RemoveIndex(
            model_name='job',
            name='jobs_job_job_id_fa7756_idx',
        ),
        migrations.RemoveIndex(
            model_name='jobapplication',
            name='jobs_jobapp_job_id_08192b_idx',
        ),
        migrations.RemoveIndex(
            model_name='jobapplication',
            name='jobs_jobapp_match_s_d65b26_idx',
        ),
        migrations.AlterUniqueTogether(
            name='jobapplication',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='job',
            name='application_count',
        ),
        migrations.RemoveField(
            model_name='job',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='job',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='job',
            name='department',
        ),
        migrations.RemoveField(
            model_name='job',
            name='employment_type',
        ),
        migrations.RemoveField(
            model_name='job',
            name='job_id',
        ),
        migrations.RemoveField(
            model_name='job',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='job',
            name='max_applications',
        ),
        migrations.RemoveField(
            model_name='job',
            name='max_experience_years',
        ),
        migrations.RemoveField(
            model_name='job',
            name='min_experience_years',
        ),
        migrations.RemoveField(
            model_name='job',
            name='nice_to_have',
        ),
        migrations.RemoveField(
            model_name='job',
            name='parsed_benefits',
        ),
        migrations.RemoveField(
            model_name='job',
            name='parsed_qualifications',
        ),
        migrations.RemoveField(
            model_name='job',
            name='published_at',
        ),
        migrations.RemoveField(
            model_name='job',
            name='remote_type',
        ),
        migrations.RemoveField(
            model_name='job',
            name='salary_currency',
        ),
        migrations.RemoveField(
            model_name='job',
            name='salary_period',
        ),
        migrations.RemoveField(
            model_name='job',
            name='view_count',
        ),
        migrations.AddField(
            model_name='job',
            name='benefits',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='company',
            field=models.CharField(default='Unknown Company', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='education_level',
            field=models.CharField(default='Bachelor', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('full-time', 'Full-time'), ('part-time', 'Part-time'), ('contract', 'Contract'), ('internship', 'Internship')], default='full-time', max_length=50),
        ),
        migrations.AddField(
            model_name='job',
            name='max_experience',
            field=models.IntegerField(blank=True, help_text='Maximum years of experience', null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='min_experience',
            field=models.IntegerField(default=0, help_text='Minimum years of experience'),
        ),
        migrations.AddField(
            model_name='job',
            name='parsed_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='parsed_education_level',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='parsed_is_remote',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='parsed_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='parsed_max_experience',
            field=models.IntegerField(blank=True, default=100),
        ),
        migrations.AddField(
            model_name='job',
            name='parsed_min_experience',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='skills_preferred',
            field=models.TextField(blank=True, help_text='Comma-separated preferred skills', null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='skills_required',
            field=models.TextField(default='', help_text='Comma-separated required skills'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='application_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='experience_level',
            field=models.CharField(choices=[('entry', 'Entry Level'), ('mid', 'Mid Level'), ('senior', 'Senior Level'), ('lead', 'Lead/Principal')], default='mid', max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='job',
            name='parsed_preferred_skills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='job',
            name='parsed_required_skills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='job',
            name='parsed_responsibilities',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='requirements',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='responsibilities',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary_min',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('draft', 'Draft')], default='active', max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='candidates.candidate'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='cover_letter',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='match_details',
            field=models.JSONField(blank=True, help_text='Detailed matching breakdown', null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='match_score',
            field=models.FloatField(blank=True, help_text='AI-calculated match score (0-100)', null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('reviewing', 'Under Review'), ('shortlisted', 'Shortlisted'), ('interviewed', 'Interviewed'), ('offered', 'Offered'), ('hired', 'Hired'), ('rejected', 'Rejected')], default='applied', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='jobapplication',
            unique_together={('candidate', 'job')},
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='interview_date',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='interview_notes',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='interview_score',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='reviewed_at',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='reviewed_by',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='screening_notes',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='screening_score',
        ),
    ]
